#!/usr/bin/env bash

analyze=false
annotate=false

dune build
rm -f qasm_out/*

while :; do
    case $1 in
        --analyze)
            analyze=true
            ;;
        --annotate)
            annotate=true
            ;;
        -?*)
            printf "Unknown option: %s\n" "$1" >&2
            exit
            ;;
        *) break
    esac
    shift
done

rm -f qasm_out/*.qasm

if $analyze; then
    rm -f diagrams/circuits/*
    rm -f diagrams/sim_results/*
fi

for filename in examples/*.qunity; do
    echo ====================
    echo $filename
    if $annotate; then
        ./qunity-compile $filename --nobuild --annotate
    else
        ./qunity-compile $filename --nobuild
    fi
    echo
done

if $analyze; then
    echo ====================
    python3 qasm_analyze.py qasm_out
fi
