#!/usr/bin/env bash

# Include the following in your ~/.inputrc:
#   set enable-bracketed-paste off
# and also optionally:
#   set blink-matching-paren off

ocamlstring=false

while :; do
    case $1 in
        --ocamlstring)
            ocamlstring=true
            ;;
        -?*)
            printf "Unknown option: %s\n" "$1" >&2
            exit
            ;;
        *) break
    esac
    shift
done

dune build
rlwrap -ppurple ./_build/default/bin/qunity_interact.exe $ocamlstring
