#!/usr/bin/env bash

RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
NC="\033[0m"

dobuild=true
analyze=false
debug=false
annotate=false
optimize=true
in_filename=$1
out_filename="qasm_out/$(basename $in_filename ".qunity").qasm"
shift

while :; do
    case $1 in
        --nobuild)
            dobuild=false
            ;;
        --analyze)
            analyze=true
            ;;
        --debug)
            debug=true
            ;;
        --annotate)
            annotate=true
            ;;
        --noopt)
            optimize=false
            ;;
        -o)
            out_filename=$2
            shift
            ;;
        -?*)
            printf "Unknown option: %s\n" "$1" >&2
            exit
            ;;
        *) break
    esac
    shift
done

if $dobuild; then
    dune build
fi

echo "Compiling to QASM"
./_build/default/bin/qunity_compile_qasm.exe $in_filename $out_filename $debug $annotate $optimize
status=$?
if [ $status -eq 1 ]; then
    echo -e "${YELLOW}Invalid program${NC}"
elif [ $status -eq 0 ]; then
    echo -e "${GREEN}Compilation done${NC}"
    echo $out_filename
    if $analyze; then
        echo
        python3 qasm_analyze.py $out_filename
    fi
else
    echo -e "${RED}Compiler error${NC}"
fi
