#!/usr/bin/env bash

RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
NC="\033[0m"

dune build
for filename in examples/*.qunity; do
    echo ====================
    echo $filename
    echo
    ./_build/default/bin/qunity_simulate.exe $filename
    status=$?
    if [ $status -eq 1 ]; then
        echo -e "\n${YELLOW}Invalid program${NC}\n"
    elif [ $status -ne 0 ]; then
        echo -e "\n${RED}Simulator error${NC}\n"
    fi
done
