OPENQASM 3.0;
include "stdgates.inc";
bit[5] out;
bit[0] err;
qubit[5] q;
h q[0];
cx q[0], q[1];
cx q[1], q[2];
cx q[1], q[3];
h q[3];
cx q[2], q[4];
x q[2];
out[0] = measure q[0];
out[1] = measure q[1];
out[2] = measure q[3];
out[3] = measure q[2];
out[4] = measure q[4];
