OPENQASM 3.0;
include "stdgates.inc";
qubit[13] q;
bit[4] out;
bit[1] err;
x q[1];
x q[3];
h q[4];
negctrl @ swap q[4], q[0], q[1];
reset q[4];
h q[4];
negctrl @ swap q[4], q[0], q[2];
reset q[4];
h q[4];
negctrl @ swap q[4], q[0], q[3];
reset q[4];
h q[4];
negctrl @ swap q[4], q[1], q[2];
reset q[4];
h q[4];
negctrl @ swap q[4], q[1], q[3];
reset q[4];
h q[4];
negctrl @ swap q[4], q[2], q[3];
reset q[4];
h q[4];
negctrl @ swap q[4], q[0], q[1];
reset q[4];
h q[4];
negctrl @ swap q[4], q[0], q[2];
reset q[4];
h q[4];
negctrl @ swap q[4], q[0], q[3];
reset q[4];
h q[4];
negctrl @ swap q[4], q[1], q[2];
reset q[4];
h q[4];
negctrl @ swap q[4], q[1], q[3];
reset q[4];
h q[4];
negctrl @ swap q[4], q[2], q[3];
reset q[4];
h q[4];
negctrl @ swap q[4], q[0], q[1];
reset q[4];
h q[4];
negctrl @ swap q[4], q[0], q[2];
reset q[4];
h q[4];
negctrl @ swap q[4], q[0], q[3];
reset q[4];
h q[4];
negctrl @ swap q[4], q[1], q[2];
reset q[4];
h q[4];
negctrl @ swap q[4], q[1], q[3];
reset q[4];
h q[4];
negctrl @ swap q[4], q[2], q[3];
reset q[4];
h q[4];
negctrl @ swap q[4], q[0], q[1];
reset q[4];
h q[4];
negctrl @ swap q[4], q[0], q[2];
reset q[4];
h q[4];
negctrl @ swap q[4], q[0], q[3];
reset q[4];
h q[4];
negctrl @ swap q[4], q[1], q[2];
reset q[4];
h q[4];
negctrl @ swap q[4], q[1], q[3];
reset q[4];
h q[4];
negctrl @ swap q[4], q[2], q[3];
reset q[4];
ctrl @ x q[0], q[4];
ctrl @ x q[1], q[5];
ctrl @ x q[2], q[6];
ctrl @ x q[3], q[7];
ctrl @ x q[1], q[8];
negctrl @ x q[0], q[9];
ctrl @ ctrl @ x q[0], q[1], q[9];
reset q[0];
reset q[1];
negctrl @ swap q[9], q[0], q[2];
negctrl @ swap q[9], q[0], q[3];
negctrl @ swap q[9], q[0], q[8];
ctrl @ ctrl @ x q[9], q[2], q[0];
ctrl @ negctrl @ x q[9], q[8], q[1];
ctrl @ ctrl @ ctrl @ x q[9], q[8], q[2], q[1];
ctrl @ negctrl @ swap q[9], q[1], q[0], q[10];
ctrl @ negctrl @ swap q[9], q[1], q[0], q[3];
ctrl @ ctrl @ ctrl @ x q[9], q[1], q[3], q[10];
ctrl @ ctrl @ negctrl @ x q[9], q[1], q[0], q[11];
ctrl @ ctrl @ ctrl @ ctrl @ x q[9], q[1], q[0], q[3], q[11];
ctrl @ ctrl @ ctrl @ x q[9], q[1], q[11], q[12];
ctrl @ ctrl @ swap q[9], q[1], q[3], q[10];
ctrl @ ctrl @ swap q[9], q[1], q[3], q[12];
ctrl @ x q[9], q[1];
ctrl @ negctrl @ swap q[9], q[1], q[0], q[3];
ctrl @ negctrl @ swap q[9], q[1], q[0], q[12];
ctrl @ negctrl @ swap q[9], q[1], q[0], q[11];
ctrl @ ctrl @ swap q[9], q[1], q[0], q[3];
ctrl @ swap q[9], q[0], q[10];
ctrl @ x q[9], q[1];
ctrl @ negctrl @ swap q[9], q[1], q[10], q[12];
ctrl @ negctrl @ swap q[9], q[1], q[10], q[11];
ctrl @ swap q[9], q[0], q[10];
ctrl @ swap q[9], q[0], q[11];
ctrl @ swap q[9], q[0], q[12];
ctrl @ swap q[9], q[0], q[2];
ctrl @ swap q[9], q[0], q[8];
ctrl @ swap q[9], q[0], q[3];
ctrl @ swap q[9], q[0], q[1];
reset q[9];
reset q[3];
reset q[8];
reset q[0];
reset q[1];
reset q[10];
reset q[11];
reset q[12];
x q[2];
err[0] = measure q[2];
reset q[2];
out[0] = measure q[4];
out[1] = measure q[5];
out[2] = measure q[6];
out[3] = measure q[7];
