OPENQASM 3.0;
include "stdgates.inc";
qubit[11] q;
bit[4] out;
bit[0] err;
ctrl @ x q[0], q[4];
ctrl @ x q[1], q[5];
ctrl @ x q[2], q[6];
ctrl @ x q[3], q[7];
ctrl @ ctrl @ swap q[4], q[5], q[7], q[8];
ctrl @ ctrl @ swap q[4], q[5], q[6], q[7];
ctrl @ ctrl @ swap q[4], q[5], q[6], q[8];
ctrl @ ctrl @ swap q[4], q[5], q[8], q[9];
ctrl @ negctrl @ swap q[4], q[5], q[6], q[8];
ctrl @ negctrl @ swap q[4], q[5], q[6], q[10];
ctrl @ swap q[4], q[8], q[9];
ctrl @ swap q[4], q[6], q[7];
negctrl @ swap q[4], q[0], q[5];
negctrl @ swap q[4], q[0], q[1];
negctrl @ swap q[4], q[0], q[6];
negctrl @ swap q[4], q[0], q[2];
negctrl @ swap q[4], q[0], q[7];
negctrl @ swap q[4], q[0], q[3];
ctrl @ negctrl @ swap q[4], q[5], q[0], q[7];
ctrl @ negctrl @ swap q[4], q[5], q[0], q[3];
ctrl @ negctrl @ swap q[4], q[5], q[0], q[2];
ctrl @ negctrl @ swap q[4], q[5], q[0], q[1];
ctrl @ negctrl @ swap q[4], q[5], q[7], q[0];
ctrl @ negctrl @ swap q[4], q[5], q[7], q[1];
ctrl @ negctrl @ swap q[4], q[5], q[7], q[2];
ctrl @ negctrl @ swap q[4], q[5], q[7], q[3];
negctrl @ swap q[4], q[5], q[0];
negctrl @ swap q[4], q[5], q[3];
negctrl @ swap q[4], q[5], q[7];
negctrl @ swap q[4], q[5], q[2];
negctrl @ swap q[4], q[5], q[6];
negctrl @ swap q[4], q[5], q[1];
ctrl @ x q[4], q[5];
ctrl @ ctrl @ swap q[4], q[5], q[8], q[9];
ctrl @ ctrl @ swap q[4], q[5], q[7], q[9];
ctrl @ ctrl @ swap q[4], q[5], q[7], q[8];
ctrl @ x q[4], q[5];
ctrl @ ctrl @ swap q[4], q[5], q[6], q[7];
ctrl @ ctrl @ swap q[4], q[5], q[6], q[10];
ctrl @ ctrl @ swap q[4], q[5], q[8], q[10];
ctrl @ x q[4], q[5];
ctrl @ negctrl @ swap q[4], q[5], q[6], q[8];
ctrl @ x q[4], q[5];
ctrl @ swap q[4], q[8], q[10];
ctrl @ swap q[4], q[8], q[9];
ctrl @ swap q[4], q[6], q[7];
ctrl @ x q[3], q[7];
ctrl @ x q[2], q[6];
ctrl @ x q[1], q[5];
ctrl @ x q[0], q[4];
out[0] = measure q[0];
out[1] = measure q[1];
out[2] = measure q[2];
out[3] = measure q[3];
