OPENQASM 3.0;
include "stdgates.inc";
qubit[12] q;
bit[2] out;
bit[10] err;
h q[0];
ctrl @ x q[0], q[1];
ctrl @ x q[1], q[3];
negctrl @ swap q[1], q[2], q[3];
ctrl @ swap q[1], q[3], q[4];
negctrl @ swap q[1], q[3], q[4];
negctrl @ swap q[1], q[6], q[4];
ctrl @ x q[1], q[4];
ctrl @ x q[1], q[7];
negctrl @ swap q[1], q[5], q[7];
negctrl @ swap q[1], q[10], q[7];
ctrl @ swap q[1], q[10], q[7];
negctrl @ swap q[1], q[9], q[10];
ctrl @ x q[1], q[10];
ctrl @ x q[8], q[1];
out[0] = measure q[8];
out[1] = measure q[11];
err[0] = measure q[0];
err[1] = measure q[1];
err[2] = measure q[2];
err[3] = measure q[3];
err[4] = measure q[4];
err[5] = measure q[5];
err[6] = measure q[6];
err[7] = measure q[7];
err[8] = measure q[9];
err[9] = measure q[10];
