OPENQASM 3.0;
include "stdgates.inc";
qubit[9] q;
bit[5] out;
bit[4] err;
h q[0];
h q[1];
h q[2];
h q[3];
h q[4];
x q[2];
x q[1];
x q[5];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5];
negctrl @ gphase(0) q[5];
ctrl @ gphase(pi) q[5];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5];
x q[5];
x q[1];
x q[2];
h q[4];
h q[3];
h q[2];
h q[1];
h q[0];
x q[6];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[6];
negctrl @ gphase(0) q[6];
ctrl @ gphase(pi) q[6];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[6];
x q[6];
h q[0];
h q[1];
h q[2];
h q[3];
h q[4];
x q[2];
x q[1];
x q[7];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[7];
negctrl @ gphase(0) q[7];
ctrl @ gphase(pi) q[7];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[7];
x q[7];
x q[1];
x q[2];
h q[4];
h q[3];
h q[2];
h q[1];
h q[0];
x q[8];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[8];
negctrl @ gphase(0) q[8];
ctrl @ gphase(pi) q[8];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[8];
x q[8];
h q[0];
h q[1];
h q[2];
h q[3];
h q[4];
out[0] = measure q[0];
out[1] = measure q[1];
out[2] = measure q[2];
out[3] = measure q[3];
out[4] = measure q[4];
err[0] = measure q[5];
err[1] = measure q[6];
err[2] = measure q[7];
err[3] = measure q[8];
