OPENQASM 3.0;
include "stdgates.inc";
qubit[10] q;
bit[5] out;
bit[0] err;
h q[0];
h q[1];
h q[2];
h q[3];
h q[4];
x q[8];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ x q[4], q[3], q[2], q[1], q[0], q[6];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ swap q[4], q[3], q[2], q[1], q[0], q[7], q[8];
negctrl @ swap q[6], q[7], q[9];
z q[7];
negctrl @ swap q[6], q[7], q[9];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ swap q[4], q[3], q[2], q[1], q[0], q[7], q[8];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ x q[4], q[3], q[2], q[1], q[0], q[6];
h q[4];
h q[3];
h q[2];
h q[1];
h q[0];
x q[5];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5];
z q[5];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5];
h q[0];
h q[1];
h q[2];
h q[3];
h q[4];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ x q[4], q[3], q[2], q[1], q[0], q[6];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ swap q[4], q[3], q[2], q[1], q[0], q[7], q[8];
negctrl @ swap q[6], q[7], q[9];
z q[7];
negctrl @ swap q[6], q[7], q[9];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ swap q[4], q[3], q[2], q[1], q[0], q[7], q[8];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ x q[4], q[3], q[2], q[1], q[0], q[6];
h q[4];
h q[3];
h q[2];
h q[1];
h q[0];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5];
z q[5];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5];
h q[0];
h q[1];
h q[2];
h q[3];
h q[4];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ x q[4], q[3], q[2], q[1], q[0], q[6];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ swap q[4], q[3], q[2], q[1], q[0], q[7], q[8];
negctrl @ swap q[6], q[7], q[9];
z q[7];
negctrl @ swap q[6], q[7], q[9];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ swap q[4], q[3], q[2], q[1], q[0], q[7], q[8];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ x q[4], q[3], q[2], q[1], q[0], q[6];
h q[4];
h q[3];
h q[2];
h q[1];
h q[0];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5];
z q[5];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5];
h q[0];
h q[1];
h q[2];
h q[3];
h q[4];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ x q[4], q[3], q[2], q[1], q[0], q[6];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ swap q[4], q[3], q[2], q[1], q[0], q[7], q[8];
negctrl @ swap q[6], q[7], q[9];
z q[7];
negctrl @ swap q[6], q[7], q[9];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ swap q[4], q[3], q[2], q[1], q[0], q[7], q[8];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ x q[4], q[3], q[2], q[1], q[0], q[6];
x q[8];
h q[4];
h q[3];
h q[2];
h q[1];
h q[0];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5];
z q[5];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5];
x q[5];
h q[0];
h q[1];
h q[2];
h q[3];
h q[4];
out[0] = measure q[0];
out[1] = measure q[1];
out[2] = measure q[2];
out[3] = measure q[3];
out[4] = measure q[4];
