OPENQASM 3.0;
include "stdgates.inc";
qubit[4] q;
bit[3] out;
bit[1] err;
h q[0];
h q[1];
h q[2];
x q[1];
x q[3];
negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3];
negctrl @ gphase(pi) q[3];
ctrl @ gphase(0) q[3];
negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3];
x q[3];
x q[1];
h q[0];
h q[1];
h q[2];
out[0] = measure q[0];
out[1] = measure q[1];
out[2] = measure q[2];
err[0] = measure q[3];
