OPENQASM 3.0;
include "stdgates.inc";
qubit[4] q;
bit[1] out;
bit[0] err;
// left prep [0]
// left out [0]
// u3 in [0]
h q[0];
// u3 out [0]
// adjoint in [0]
// adjoint out [0]
// context_partition in [0]
// context_partition out [0]
// context_partition in [0]
// context_partition out [0]
// share in [0]
// share prep [1]
ctrl @ x q[0], q[1];
// share out [0, 1]
// adjoint in [0]
// context_partition out [0]
// context_partition in [0]
// adjoint out [0]
// adjoint in [1]
// context_partition out [1]
// context_partition in [1]
// adjoint out [1]
// context_partition in [1]
// context_partition out [1]
// share in [1]
// share prep [2]
ctrl @ x q[1], q[2];
// share out [1, 2]
// adjoint in [1]
// context_partition out [1]
// context_partition in [1]
// adjoint out [1]
// adjoint in [2]
// context_partition out [2]
// context_partition in [2]
// adjoint out [2]
// context_partition in [2]
// context_partition out [2]
// share in [2]
// share prep [3]
ctrl @ x q[2], q[3];
// share out [2, 3]
// adjoint in [2]
// context_partition out [2]
// context_partition in [2]
// adjoint out [2]
// adjoint in [3]
// context_partition out [3]
// context_partition in [3]
// adjoint out [3]
// pair in [2, 3]
// pair out [2, 3]
// pair in [1, 2, 3]
// pair out [1, 2, 3]
// pair in [0, 1, 2, 3]
// pair out [0, 1, 2, 3]
// adjoint in [0, 1, 2, 3]
// pair out [0, 1, 2, 3]
// pair in [0, 1, 2, 3]
// pair out [1, 2, 3]
// pair in [1, 2, 3]
// pair out [2, 3]
// pair in [2, 3]
// adjoint out [3]
// context_partition in [3]
// context_partition out [3]
// adjoint in [3]
// adjoint out [2]
// context_partition in [2]
// context_partition out [2]
// adjoint in [2]
// context_partition out [2, 3]
// context_partition in [2, 3]
// context_partition out [2, 3]
// context_partition in [2, 3]
// adjoint out [2, 3]
// context_partition in [2, 3]
// context_partition out [2, 3]
// adjoint in [2, 3]
// adjoint out [1]
// context_partition in [1]
// context_partition out [1]
// adjoint in [1]
// context_partition out [1, 2, 3]
// context_partition in [1, 2, 3]
// context_partition out [1, 2, 3]
// context_partition in [1, 2, 3]
// adjoint out [1, 2, 3]
// context_partition in [1, 2, 3]
// context_partition out [1, 2, 3]
// adjoint in [1, 2, 3]
// adjoint out [0]
// context_partition in [0]
// context_partition out [0]
// adjoint in [0]
// context_partition out [0, 1, 2, 3]
// context_partition in [0, 1, 2, 3]
// context_partition out [0, 1, 2, 3]
// context_partition in [0, 1, 2, 3]
// adjoint out [0, 1, 2, 3]
// context_partition in [0, 1, 2, 3]
// context_partition out [2, 0, 1, 3]
// discard in [0, 1, 3]
reset q[0];
reset q[1];
reset q[3];
// discard garb [0, 1, 3]
out[0] = measure q[2];
