OPENQASM 3.0;
include "stdgates.inc";
qubit[5] q;
bit[2] out;
bit[3] err;
x q[0];
ctrl @ x q[0], q[1];
ctrl @ x q[0], q[1];
ctrl @ x q[0], q[2];
ctrl @ x q[0], q[2];
ctrl @ x q[0], q[3];
ctrl @ x q[0], q[3];
ctrl @ x q[0], q[4];
out[0] = measure q[0];
out[1] = measure q[4];
err[0] = measure q[1];
err[1] = measure q[2];
err[2] = measure q[3];
