OPENQASM 3.0;
include "stdgates.inc";
qubit[2] q;
bit[1] out;
bit[0] err;
// left prep [0]
// left out [0]
// adjoint in [0]
// adjoint out [0]
// context_partition in [0]
// context_partition out [0]
// context_partition in [0]
// context_partition out [0]
// share in [0]
// share prep [1]
ctrl @ x q[0], q[1];
// share out [0, 1]
// adjoint in [0]
// context_partition out [0]
// context_partition in [0]
// adjoint out [0]
// adjoint in [1]
// context_partition out [1]
// context_partition in [1]
// adjoint out [1]
// pair in [0, 1]
// pair out [0, 1]
// adjoint in [0, 1]
// pair out [0, 1]
// pair in [0, 1]
// adjoint out [1]
// context_partition in [1]
// context_partition out [1]
// adjoint in [1]
// adjoint out [0]
// context_partition in [0]
// context_partition out [0]
// adjoint in [0]
// context_partition out [0, 1]
// context_partition in [0, 1]
// context_partition out [0, 1]
// context_partition in [0, 1]
// adjoint out [0, 1]
// context_partition in [0, 1]
// context_partition out [0, 1]
// discard in [1]
reset q[1];
// discard garb [1]
out[0] = measure q[0];
