OPENQASM 3.0;
include "stdgates.inc";
qubit[2] q;
bit[2] out;
bit[3] err;
x q[0];
err[0] = measure q[1];
reset q[1];
err[1] = measure q[1];
reset q[1];
err[2] = measure q[1];
reset q[1];
ctrl @ x q[0], q[1];
out[0] = measure q[0];
out[1] = measure q[1];
