OPENQASM 3.0;
include "stdgates.inc";
qubit[4] q;
bit[1] out;
bit[0] err;
h q[0];
ctrl @ x q[0], q[1];
ctrl @ x q[1], q[2];
ctrl @ x q[2], q[3];
reset q[0];
reset q[1];
reset q[3];
out[0] = measure q[2];
