OPENQASM 3.0;
include "stdgates.inc";
qubit[12] q;
bit[3] out;
bit[0] err;
h q[0];
h q[1];
h q[2];
U(0.78539816339744827900, 0.00000000000000000000, 0.00000000000000000000) q[3];
ctrl @ x q[3], q[4];
ctrl @ x q[1], q[5];
ctrl @ x q[2], q[6];
negctrl @ ctrl @ swap q[0], q[5], q[6], q[7];
ctrl @ negctrl @ swap q[0], q[5], q[6], q[7];
ctrl @ negctrl @ swap q[5], q[6], q[4], q[8];
negctrl @ negctrl @ ctrl @ swap q[0], q[5], q[6], q[4], q[7];
negctrl @ negctrl @ ctrl @ swap q[0], q[5], q[6], q[8], q[9];
negctrl @ ctrl @ negctrl @ swap q[0], q[5], q[6], q[4], q[8];
negctrl @ ctrl @ negctrl @ swap q[0], q[5], q[6], q[4], q[7];
negctrl @ ctrl @ swap q[0], q[5], q[8], q[9];
ctrl @ ctrl @ negctrl @ swap q[0], q[5], q[6], q[4], q[8];
ctrl @ negctrl @ swap q[0], q[6], q[4], q[7];
ctrl @ ctrl @ negctrl @ swap q[0], q[5], q[6], q[8], q[9];
ctrl @ negctrl @ swap q[0], q[5], q[8], q[9];
negctrl @ ctrl @ swap q[0], q[5], q[4], q[6];
negctrl @ ctrl @ swap q[0], q[5], q[4], q[7];
negctrl @ ctrl @ swap q[0], q[5], q[7], q[9];
negctrl @ ctrl @ swap q[0], q[5], q[7], q[8];
ctrl @ x q[0], q[5];
ctrl @ ctrl @ swap q[0], q[5], q[4], q[6];
ctrl @ ctrl @ swap q[0], q[5], q[4], q[7];
ctrl @ ctrl @ swap q[0], q[5], q[7], q[9];
ctrl @ ctrl @ swap q[0], q[5], q[7], q[8];
ctrl @ x q[0], q[5];
negctrl @ negctrl @ ctrl @ swap q[0], q[5], q[6], q[4], q[7];
negctrl @ negctrl @ ctrl @ swap q[0], q[5], q[6], q[7], q[8];
ctrl @ x q[0], q[5];
ctrl @ negctrl @ x q[0], q[5], q[6];
ctrl @ negctrl @ ctrl @ swap q[0], q[5], q[6], q[4], q[7];
ctrl @ negctrl @ ctrl @ swap q[0], q[5], q[6], q[7], q[8];
ctrl @ negctrl @ x q[0], q[5], q[6];
ctrl @ x q[0], q[5];
negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[5], q[6], q[4], q[8];
negctrl @ negctrl @ negctrl @ negctrl @ swap q[0], q[5], q[6], q[4], q[7], q[8];
ctrl @ ctrl @ ctrl @ ctrl @ x q[0], q[5], q[6], q[4], q[7];
ctrl @ ctrl @ ctrl @ ctrl @ x q[0], q[5], q[6], q[4], q[8];
ctrl @ ctrl @ ctrl @ ctrl @ swap q[0], q[5], q[6], q[4], q[7], q[8];
negctrl @ negctrl @ negctrl @ swap q[0], q[5], q[6], q[9], q[10];
negctrl @ negctrl @ ctrl @ swap q[0], q[5], q[6], q[4], q[9];
ctrl @ ctrl @ negctrl @ swap q[0], q[5], q[6], q[4], q[9];
ctrl @ ctrl @ ctrl @ swap q[0], q[5], q[6], q[9], q[10];
negctrl @ ctrl @ swap q[0], q[5], q[4], q[11];
negctrl @ ctrl @ swap q[0], q[5], q[4], q[6];
negctrl @ ctrl @ swap q[0], q[5], q[9], q[10];
negctrl @ ctrl @ swap q[0], q[5], q[9], q[11];
ctrl @ x q[0], q[5];
ctrl @ ctrl @ swap q[0], q[5], q[4], q[11];
ctrl @ ctrl @ swap q[0], q[5], q[4], q[6];
ctrl @ ctrl @ swap q[0], q[5], q[9], q[10];
ctrl @ ctrl @ swap q[0], q[5], q[9], q[11];
ctrl @ x q[0], q[5];
negctrl @ negctrl @ ctrl @ swap q[0], q[5], q[6], q[4], q[9];
negctrl @ negctrl @ ctrl @ swap q[0], q[5], q[6], q[4], q[11];
negctrl @ negctrl @ ctrl @ swap q[0], q[5], q[6], q[10], q[11];
negctrl @ ctrl @ negctrl @ swap q[0], q[5], q[6], q[4], q[9];
negctrl @ ctrl @ negctrl @ swap q[0], q[5], q[6], q[4], q[11];
negctrl @ ctrl @ swap q[0], q[5], q[10], q[11];
ctrl @ x q[0], q[5];
ctrl @ negctrl @ x q[0], q[5], q[6];
ctrl @ negctrl @ ctrl @ swap q[0], q[5], q[6], q[4], q[9];
ctrl @ negctrl @ ctrl @ swap q[0], q[5], q[6], q[4], q[11];
ctrl @ negctrl @ ctrl @ swap q[0], q[5], q[6], q[10], q[11];
ctrl @ negctrl @ x q[0], q[5], q[6];
ctrl @ ctrl @ negctrl @ swap q[0], q[5], q[6], q[4], q[9];
ctrl @ ctrl @ negctrl @ swap q[0], q[5], q[6], q[4], q[11];
ctrl @ ctrl @ swap q[0], q[5], q[10], q[11];
ctrl @ x q[0], q[5];
negctrl @ negctrl @ x q[0], q[5], q[6];
negctrl @ negctrl @ negctrl @ swap q[0], q[5], q[6], q[4], q[10];
negctrl @ negctrl @ x q[0], q[5], q[6];
ctrl @ negctrl @ negctrl @ swap q[0], q[5], q[6], q[4], q[10];
ctrl @ negctrl @ swap q[5], q[6], q[4], q[10];
negctrl @ x q[0], q[5];
negctrl @ negctrl @ swap q[0], q[5], q[6], q[9];
negctrl @ x q[0], q[5];
ctrl @ negctrl @ swap q[0], q[5], q[6], q[9];
ctrl @ x q[2], q[6];
ctrl @ x q[1], q[5];
ctrl @ x q[3], q[4];
negctrl @ swap q[7], q[1], q[0];
negctrl @ swap q[7], q[1], q[3];
negctrl @ swap q[7], q[1], q[8];
negctrl @ swap q[7], q[1], q[2];
ctrl @ negctrl @ x q[7], q[8], q[0];
ctrl @ negctrl @ negctrl @ x q[7], q[8], q[0], q[1];
ctrl @ negctrl @ negctrl @ negctrl @ x q[7], q[8], q[0], q[1], q[2];
ctrl @ negctrl @ x q[7], q[8], q[3];
ctrl @ negctrl @ swap q[7], q[8], q[1], q[0];
ctrl @ negctrl @ swap q[7], q[8], q[1], q[3];
ctrl @ negctrl @ swap q[7], q[8], q[1], q[2];
ctrl @ ctrl @ negctrl @ negctrl @ x q[7], q[8], q[0], q[1], q[2];
ctrl @ ctrl @ negctrl @ x q[7], q[8], q[0], q[1];
ctrl @ ctrl @ x q[7], q[8], q[0];
ctrl @ ctrl @ x q[7], q[8], q[3];
ctrl @ ctrl @ swap q[7], q[8], q[1], q[0];
ctrl @ ctrl @ swap q[7], q[8], q[1], q[3];
ctrl @ ctrl @ swap q[7], q[8], q[1], q[2];
negctrl @ ctrl @ x q[7], q[8], q[4];
negctrl @ negctrl @ negctrl @ negctrl @ x q[7], q[4], q[3], q[0], q[1];
negctrl @ negctrl @ negctrl @ x q[7], q[4], q[3], q[0];
negctrl @ negctrl @ x q[7], q[4], q[3];
negctrl @ negctrl @ swap q[7], q[4], q[1], q[0];
negctrl @ negctrl @ swap q[7], q[4], q[1], q[3];
negctrl @ ctrl @ x q[7], q[4], q[3];
negctrl @ ctrl @ negctrl @ x q[7], q[4], q[3], q[0];
negctrl @ ctrl @ negctrl @ negctrl @ x q[7], q[4], q[3], q[0], q[1];
negctrl @ ctrl @ swap q[7], q[4], q[1], q[0];
negctrl @ ctrl @ swap q[7], q[4], q[1], q[3];
negctrl @ swap q[7], q[1], q[8];
negctrl @ ctrl @ x q[7], q[1], q[4];
negctrl @ swap q[7], q[8], q[3];
negctrl @ swap q[7], q[8], q[0];
negctrl @ swap q[7], q[8], q[1];
negctrl @ swap q[7], q[8], q[2];
reset q[7];
reset q[8];
reset q[2];
out[0] = measure q[1];
out[1] = measure q[0];
out[2] = measure q[3];
