OPENQASM 3.0;
include "stdgates.inc";
qubit[11] q;
bit[3] out;
bit[0] err;
h q[0];
h q[1];
h q[2];
U(0.78539816339744827900, 0.00000000000000000000, 0.00000000000000000000) q[3];
ctrl @ x q[3], q[4];
ctrl @ x q[0], q[5];
ctrl @ x q[1], q[6];
ctrl @ x q[2], q[7];
negctrl @ ctrl @ swap q[0], q[1], q[2], q[8];
ctrl @ negctrl @ swap q[0], q[1], q[2], q[8];
ctrl @ negctrl @ swap q[1], q[2], q[3], q[9];
negctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[3], q[8];
negctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[9], q[10];
negctrl @ ctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[9];
negctrl @ ctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[8];
negctrl @ ctrl @ swap q[0], q[1], q[9], q[10];
ctrl @ ctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[9];
ctrl @ negctrl @ swap q[0], q[2], q[3], q[8];
ctrl @ ctrl @ negctrl @ swap q[0], q[1], q[2], q[9], q[10];
ctrl @ negctrl @ swap q[0], q[1], q[9], q[10];
negctrl @ ctrl @ swap q[0], q[1], q[2], q[8];
negctrl @ ctrl @ swap q[0], q[1], q[2], q[3];
negctrl @ ctrl @ swap q[0], q[1], q[8], q[10];
negctrl @ ctrl @ swap q[0], q[1], q[8], q[9];
ctrl @ x q[0], q[1];
ctrl @ ctrl @ swap q[0], q[1], q[2], q[8];
ctrl @ ctrl @ swap q[0], q[1], q[2], q[3];
ctrl @ ctrl @ swap q[0], q[1], q[8], q[10];
ctrl @ ctrl @ swap q[0], q[1], q[8], q[9];
ctrl @ x q[0], q[1];
negctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[3], q[8];
negctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[8], q[9];
ctrl @ x q[0], q[1];
ctrl @ negctrl @ x q[0], q[1], q[2];
ctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[3], q[8];
ctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[8], q[9];
ctrl @ negctrl @ x q[0], q[1], q[2];
ctrl @ x q[0], q[1];
negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[5];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[5], q[6];
negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[5], q[6], q[7];
negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4];
negctrl @ negctrl @ negctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[7];
negctrl @ negctrl @ negctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[6];
negctrl @ negctrl @ negctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[5];
negctrl @ negctrl @ negctrl @ ctrl @ ctrl @ x q[0], q[1], q[2], q[3], q[4], q[8];
negctrl @ negctrl @ negctrl @ ctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7];
negctrl @ negctrl @ negctrl @ ctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5], q[6];
negctrl @ negctrl @ negctrl @ ctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5];
negctrl @ negctrl @ negctrl @ ctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[5], q[8];
negctrl @ negctrl @ negctrl @ ctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[5], q[7];
negctrl @ negctrl @ negctrl @ ctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[5], q[6];
negctrl @ negctrl @ negctrl @ ctrl @ ctrl @ x q[0], q[1], q[2], q[3], q[4], q[5];
negctrl @ negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5], q[6];
negctrl @ negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7];
negctrl @ negctrl @ negctrl @ ctrl @ ctrl @ swap q[0], q[1], q[2], q[3], q[4], q[5], q[8];
negctrl @ negctrl @ negctrl @ ctrl @ ctrl @ swap q[0], q[1], q[2], q[3], q[4], q[5], q[7];
negctrl @ negctrl @ negctrl @ ctrl @ ctrl @ swap q[0], q[1], q[2], q[3], q[4], q[5], q[6];
negctrl @ negctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[3], q[4], q[8];
negctrl @ negctrl @ ctrl @ ctrl @ x q[0], q[1], q[2], q[4], q[8];
negctrl @ negctrl @ ctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[4], q[5], q[6], q[7];
negctrl @ negctrl @ ctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[4], q[5], q[6];
negctrl @ negctrl @ ctrl @ negctrl @ x q[0], q[1], q[2], q[4], q[5];
negctrl @ negctrl @ ctrl @ negctrl @ swap q[0], q[1], q[2], q[4], q[5], q[8];
negctrl @ negctrl @ ctrl @ negctrl @ swap q[0], q[1], q[2], q[4], q[5], q[7];
negctrl @ negctrl @ ctrl @ negctrl @ swap q[0], q[1], q[2], q[4], q[5], q[6];
negctrl @ negctrl @ ctrl @ ctrl @ x q[0], q[1], q[2], q[4], q[5];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ x q[0], q[1], q[2], q[4], q[5], q[6];
negctrl @ negctrl @ ctrl @ ctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[4], q[5], q[6], q[7];
negctrl @ negctrl @ ctrl @ ctrl @ swap q[0], q[1], q[2], q[4], q[5], q[8];
negctrl @ negctrl @ ctrl @ ctrl @ swap q[0], q[1], q[2], q[4], q[5], q[7];
negctrl @ negctrl @ ctrl @ ctrl @ swap q[0], q[1], q[2], q[4], q[5], q[6];
negctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[4], q[8];
negctrl @ ctrl @ ctrl @ x q[0], q[1], q[4], q[8];
negctrl @ ctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[4], q[5], q[6], q[7];
negctrl @ ctrl @ negctrl @ negctrl @ x q[0], q[1], q[4], q[5], q[6];
negctrl @ ctrl @ negctrl @ x q[0], q[1], q[4], q[5];
negctrl @ ctrl @ negctrl @ swap q[0], q[1], q[4], q[5], q[8];
negctrl @ ctrl @ negctrl @ swap q[0], q[1], q[4], q[5], q[7];
negctrl @ ctrl @ negctrl @ swap q[0], q[1], q[4], q[5], q[6];
negctrl @ ctrl @ ctrl @ x q[0], q[1], q[4], q[5];
negctrl @ ctrl @ ctrl @ negctrl @ x q[0], q[1], q[4], q[5], q[6];
negctrl @ ctrl @ ctrl @ negctrl @ negctrl @ x q[0], q[1], q[4], q[5], q[6], q[7];
negctrl @ ctrl @ ctrl @ swap q[0], q[1], q[4], q[5], q[8];
negctrl @ ctrl @ ctrl @ swap q[0], q[1], q[4], q[5], q[7];
negctrl @ ctrl @ ctrl @ swap q[0], q[1], q[4], q[5], q[6];
negctrl @ ctrl @ swap q[0], q[1], q[4], q[8];
ctrl @ negctrl @ ctrl @ x q[0], q[1], q[4], q[8];
ctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[4], q[5], q[6], q[7];
ctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[4], q[5], q[6];
ctrl @ negctrl @ negctrl @ x q[0], q[1], q[4], q[5];
ctrl @ negctrl @ negctrl @ swap q[0], q[1], q[4], q[5], q[8];
ctrl @ negctrl @ negctrl @ swap q[0], q[1], q[4], q[5], q[7];
ctrl @ negctrl @ negctrl @ swap q[0], q[1], q[4], q[5], q[6];
ctrl @ negctrl @ ctrl @ x q[0], q[1], q[4], q[5];
ctrl @ negctrl @ ctrl @ negctrl @ x q[0], q[1], q[4], q[5], q[6];
ctrl @ negctrl @ ctrl @ negctrl @ negctrl @ x q[0], q[1], q[4], q[5], q[6], q[7];
ctrl @ negctrl @ ctrl @ swap q[0], q[1], q[4], q[5], q[8];
ctrl @ negctrl @ ctrl @ swap q[0], q[1], q[4], q[5], q[7];
ctrl @ negctrl @ ctrl @ swap q[0], q[1], q[4], q[5], q[6];
ctrl @ negctrl @ swap q[0], q[1], q[4], q[8];
ctrl @ ctrl @ negctrl @ ctrl @ x q[0], q[1], q[2], q[4], q[8];
ctrl @ ctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[4], q[5], q[6], q[7];
ctrl @ ctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[4], q[5], q[6];
ctrl @ ctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[4], q[5];
ctrl @ ctrl @ negctrl @ negctrl @ swap q[0], q[1], q[2], q[4], q[5], q[8];
ctrl @ ctrl @ negctrl @ negctrl @ swap q[0], q[1], q[2], q[4], q[5], q[7];
ctrl @ ctrl @ negctrl @ negctrl @ swap q[0], q[1], q[2], q[4], q[5], q[6];
ctrl @ ctrl @ negctrl @ ctrl @ x q[0], q[1], q[2], q[4], q[5];
ctrl @ ctrl @ negctrl @ ctrl @ negctrl @ x q[0], q[1], q[2], q[4], q[5], q[6];
ctrl @ ctrl @ negctrl @ ctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[4], q[5], q[6], q[7];
ctrl @ ctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[4], q[5], q[8];
ctrl @ ctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[4], q[5], q[7];
ctrl @ ctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[4], q[5], q[6];
ctrl @ ctrl @ negctrl @ swap q[0], q[1], q[2], q[4], q[8];
ctrl @ ctrl @ ctrl @ negctrl @ ctrl @ x q[0], q[1], q[2], q[3], q[4], q[8];
ctrl @ ctrl @ ctrl @ negctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7];
ctrl @ ctrl @ ctrl @ negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5], q[6];
ctrl @ ctrl @ ctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5];
ctrl @ ctrl @ ctrl @ negctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[5], q[8];
ctrl @ ctrl @ ctrl @ negctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[5], q[7];
ctrl @ ctrl @ ctrl @ negctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[5], q[6];
ctrl @ ctrl @ ctrl @ negctrl @ ctrl @ x q[0], q[1], q[2], q[3], q[4], q[5];
ctrl @ ctrl @ ctrl @ negctrl @ ctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5], q[6];
ctrl @ ctrl @ ctrl @ negctrl @ ctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7];
ctrl @ ctrl @ ctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[3], q[4], q[5], q[8];
ctrl @ ctrl @ ctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[3], q[4], q[5], q[7];
ctrl @ ctrl @ ctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[3], q[4], q[5], q[6];
ctrl @ ctrl @ ctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[8];
ctrl @ ctrl @ ctrl @ ctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[5], q[6], q[7];
ctrl @ ctrl @ ctrl @ ctrl @ negctrl @ x q[0], q[1], q[2], q[3], q[5], q[6];
ctrl @ ctrl @ ctrl @ ctrl @ x q[0], q[1], q[2], q[3], q[5];
ctrl @ ctrl @ ctrl @ ctrl @ x q[0], q[1], q[2], q[3], q[4];
ctrl @ ctrl @ ctrl @ ctrl @ swap q[0], q[1], q[2], q[3], q[4], q[7];
ctrl @ ctrl @ ctrl @ ctrl @ swap q[0], q[1], q[2], q[3], q[4], q[6];
ctrl @ ctrl @ ctrl @ ctrl @ swap q[0], q[1], q[2], q[3], q[4], q[5];
negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3];
negctrl @ negctrl @ negctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[5];
negctrl @ negctrl @ negctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[6];
negctrl @ negctrl @ negctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[7];
negctrl @ negctrl @ negctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[8];
negctrl @ negctrl @ negctrl @ x q[0], q[1], q[2], q[3];
negctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[4], q[5];
negctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[4], q[6];
negctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[4], q[7];
negctrl @ negctrl @ ctrl @ swap q[0], q[1], q[2], q[4], q[8];
ctrl @ negctrl @ swap q[0], q[1], q[4], q[5];
ctrl @ negctrl @ swap q[0], q[1], q[4], q[6];
ctrl @ negctrl @ swap q[0], q[1], q[4], q[7];
ctrl @ negctrl @ swap q[0], q[1], q[4], q[8];
negctrl @ negctrl @ negctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[5];
negctrl @ negctrl @ negctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[6];
negctrl @ negctrl @ negctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[7];
negctrl @ negctrl @ negctrl @ negctrl @ swap q[0], q[1], q[2], q[3], q[4], q[8];
ctrl @ swap q[1], q[4], q[5];
ctrl @ swap q[1], q[4], q[6];
ctrl @ swap q[1], q[4], q[7];
ctrl @ swap q[1], q[4], q[8];
reset q[0];
reset q[1];
reset q[2];
reset q[3];
reset q[4];
reset q[8];
out[0] = measure q[7];
out[1] = measure q[6];
out[2] = measure q[5];
